.PHONY: clean All

All:
	@echo "----------Building project:[ TemperatureConverter - Debug ]----------"
	@cd "TemperatureConverter" && "$(MAKE)" -f  "TemperatureConverter.mk"
clean:
	@echo "----------Cleaning project:[ TemperatureConverter - Debug ]----------"
	@cd "TemperatureConverter" && "$(MAKE)" -f  "TemperatureConverter.mk" clean
